/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WavesSimulationTest;

import WavesSimulation.Diffraction.DiffractionSim;

class AppTest {
    
    DiffractionSim diffSim = new DiffractionSim(); 
    
    public void testDiffAngle (){
        System.out.println("Angle: ");
    }
    
    public void testDiffRadius (){
        System.out.println("Angle: ");
    }
    
}
