/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WavesSimulationTest;

import WavesSimulation.Diffraction.DiffractionSim;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;
import org.junit.jupiter.api.Test;


class DiffractionTest {
    
    private final DiffractionSim diffSim = new DiffractionSim(); 
    
    private boolean isCalculated (double num){
        return num != 0.00; 
    }
    
    @Test void diffAngleTest (){
        System.out.println("Test Angles Calculation");
        boolean expResult = true; 
        int wavelength = 380; 
        double slitDistance = 0.5; 
        int orderNum = 1; 
        boolean calcResult = isCalculated(diffSim.calculationAngle(wavelength, slitDistance, orderNum)); 
        assertEquals (expResult, calcResult); 
        fail("The test case is a prototype."); 
    }
    
    @Test void testDiffRadius (){
        System.out.println("Test Radius Calculation");
        boolean expResult = true; 
        boolean calcResult = isCalculated(diffSim.calculationDiffractionRadius()); 
        assertEquals (expResult, calcResult); 
        fail("The test case is a prototype."); 
    }
    
}
